image: maven:3.6.1

pipelines:
  default:
    - step:
        name: "Verify"
        caches:
          - maven
        script:
          - mvn -B verify
  tags:
    release-*:
      - step:
          name: "Build & Test"
          caches:
            - maven
          script:
            - mvn -B clean install
          artifacts:
            - target/foria-api-server.jar
      - step:
          name: "Deploy to AWS Elastic Beanstalk"
          deployment: staging
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "us-east-1"
                APPLICATION_NAME: "foria-api-server"
                ENVIRONMENT_NAME: "foria-api-staging"
                ZIP_FILE: "foria-api-server.jar"
                S3_BUCKET: "elasticbeanstalk-us-east-1-907328165182"
                VERSION_LABEL: "foria-api-server-$BITBUCKET_BUILD_NUMBER"