# Global Settings
spring:
    application:
        name: Foria Server
spring.profiles.active: local

# Spring Application Settings & AWS Settings
logging.config: classpath:log4j2.xml
spring.jackson.serialization.write_dates_as_timestamps: false
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
    port: 8080
    servlet:
        context-path: /
---
spring:
    profiles: local

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
spring.jpa.hibernate.ddl-auto: create

logging.config: classpath:log4j2-local.xml

# Database Connection Info
db.driver_classname: org.h2.Driver
db.jdbc: jdbc:h2:mem:foria;DB_CLOSE_ON_EXIT=FALSE
db.username: sa
db.password: sa