# Global Settings
# Spring Application Settings & AWS Settings
spring:
    application:
        name: Foria API Server
    jackson:
        property-naming-strategy: SNAKE_CASE
        logging.config: classpath:log4j2.xml
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        properties:
            hibernate:
                globally_quoted_identifiers: true
                dialect: org.hibernate.dialect.MySQL55Dialect
    mustache:
        check-template-location: false
    profiles.active: local
    datasource:
      hikari:
        maximum-pool-size: 10

server:
    port: 8080
    servlet:
        context-path: /

report.email: "info@foriatickets.com"

---
spring:
    profiles: local

spring.jpa.hibernate.ddl-auto: create

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.show_sql: false
spring.jpa.properties.hibernate.format_sql: true

logging.config: classpath:log4j2-local.xml

# Database Connection Info
db.jdbc: jdbc:h2:mem:foria;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
db.username: sa
db.password: sa

# Spotify
spotifyApiKey: spotify

# Stripe
stripeApiKey: corp_foria_stripe_secret_key

# Auth0
auth0.issuer: https://auth-test.foriatickets.com/
auth0.apiAudience: api.foriatickets.com

#FCM
fcmDatabaseUrl: https://foria-tickets.firebaseio.com
fcmKey: prod_foria_google_fcm_key

#Auth0 Management
auth0ManagementKey: corp_foria_auth0_management_key

---
spring:
    profiles: staging

# Corp Database Connection Info
db.name: foria
db.secret: corp-db-foria-user-pass
datasource:
  hikari:
    maximum-pool-size: 20

apiKeyList: corp_foria_auth0_api_key

# Spotify
spotifyApiKey: spotify

# Stripe
stripeApiKey: corp_foria_stripe_secret_key

# Auth0
auth0.issuer: https://auth-test.foriatickets.com/
auth0.apiAudience: api.foriatickets.com

#FCM
fcmDatabaseUrl: https://foria-tickets.firebaseio.com
fcmKey: prod_foria_google_fcm_key

#Auth0 Management
auth0ManagementKey: corp_foria_auth0_management_key

# Jobs
daily-event-end-report-cron: "0 0 6 */1 * ?"

---
spring:
  profiles: production

# Prod Database Connection Info
db.name: foria
db.secret: prod_db_foria
datasource:
  hikari:
    maximum-pool-size: 20

apiKeyList: prod_foria_auth0_api_key

# Spotify
spotifyApiKey: spotify

# Stripe LIVE Key
stripeApiKey: prod_foria_stripe_secret_key

# Auth0
auth0.issuer: https://auth.foriatickets.com/
auth0.apiAudience: api.foriatickets.com

#FCM
fcmDatabaseUrl: https://foria-tickets.firebaseio.com
fcmKey: prod_foria_google_fcm_key

#Auth0 Management
auth0ManagementKey: prod_foria_auth0_management_key

# Report Scheduling
daily-ticket-purchase-report-cron: "0 0 6 */1 * ?"
weekly-settlement-report-cron: "0 0 6 */1 * WED"
rolling-ticket-purchase-report-cron: "-"
daily-general-event-email-cron: "0 0 11 */1 * ?"
daily-event-end-report-cron: "0 0 6 */1 * ?"