# Global Settings
# Spring Application Settings & AWS Settings
spring:
    application:
        name: Foria API Server
    jackson:
        property-naming-strategy: SNAKE_CASE
        logging.config: classpath:log4j2.xml
        serialization.write_dates_as_timestamps: false
    jpa:
        hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
    profiles.active: local

server:
    port: 8080
    servlet:
        context-path: /
---
spring:
    profiles: local

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
spring.jpa.hibernate.ddl-auto: create

logging.config: classpath:log4j2-local.xml

# Database Connection Info
db.jdbc: jdbc:h2:mem:foria;DB_CLOSE_ON_EXIT=FALSE
db.username: sa
db.password: sa

---
spring:
    profiles: staging

# Corp Database Connection Info
db.name: foria
db.secret: corp-db-foria-user-pass
logging.config: classpath:log4j2-local.xml #TODO: REMOVE ME BEFORE PROD