# Global Settings
# Spring Application Settings & AWS Settings
spring:
    application:
        name: Foria API Server
    jackson:
        property-naming-strategy: SNAKE_CASE
        logging.config: classpath:log4j2.xml
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        properties:
            hibernate:
                globally_quoted_identifiers: true
                dialect: org.hibernate.dialect.MySQL55Dialect
    mustache:
        check-template-location: false
    profiles.active: local

server:
    port: 8080
    servlet:
        context-path: /
---
spring:
    profiles: local

spring.h2.console.enabled: true
spring.h2.console.path: /console
spring.jpa.hibernate.ddl-auto: create

spring.jpa.properties.hibernate.show_sql: false
spring.jpa.properties.hibernate.format_sql: true

logging.config: classpath:log4j2-local.xml

# Database Connection Info
db.jdbc: jdbc:h2:file:~/.h2/foria;AUTO_SERVER=TRUE
db.username: sa
db.password: sa

# Stripe
stripeApiKey: corp_foria_stripe_secret_key

---
spring:
    profiles: staging

# Corp Database Connection Info
db.name: foria
db.secret: corp-db-foria-user-pass
apiKeyList: corp_foria_auth0_api_key

# Stripe
stripeApiKey: corp_foria_stripe_secret_key